import json
import re

notebook_path = "system_blueprint.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Cell 1: Mermaid
for cell in nb["cells"]:
    if cell["cell_type"] == "code" and "mermaid_code = " in "".join(cell["source"]):
        cell["source"] = [
            "# Cell 2: The Pipeline Architecture (Mermaid Diagram)\n",
            "from IPython.display import display, Markdown\n",
            "\n",
            "mermaid_code = \"\"\"\n",
            "```mermaid\n",
            "graph TD\n",
            "    %% Cluster A: Multimodal Reasoning (Pipeline A)\n",
            "    subgraph Cluster A: Multimodal Reasoning\n",
            "        T[Text Upload]\n",
            "        P[PDF Upload]\n",
            "        I[Image Upload]\n",
            "        \n",
            "        Extract[Extraction: PyMuPDF / LLaVA]\n",
            "        Te[Teacher Node: Qwen 2.5]\n",
            "        R[Reviewer Node]\n",
            "        EndA[END]\n",
            "        \n",
            "        T --> Extract\n",
            "        P --> Extract\n",
            "        I --> Extract\n",
            "        Extract --> Te\n",
            "        Te --> R\n",
            "        R --> EndA\n",
            "    end\n",
            "\n",
            "    %% Cluster B: Autonomous Code Execution (Pipeline B)\n",
            "    subgraph Cluster B: Autonomous Code Execution\n",
            "        C[Editor Input: Run Code]\n",
            "        MD[Manual Debug Button]\n",
            "        \n",
            "        E2B[E2B Sandbox Node]\n",
            "        Debug[DeepSeek Debugger Node]\n",
            "        ErrorCheck{execution_error?}\n",
            "        EndB[END]\n",
            "        \n",
            "        C --> E2B\n",
            "        MD --> Debug\n",
            "        \n",
            "        E2B --> ErrorCheck\n",
            "        ErrorCheck -- Yes --> EndB\n",
            "        ErrorCheck -- No --> EndB\n",
            "        \n",
            "        Debug --> E2B\n",
            "    end\n",
            "```\n",
            "\"\"\"\n",
            "\n",
            "display(Markdown(mermaid_code))\n",
            "print(\"Cell 2 Executed: Architecture Diagram Rendered.\")"
        ]
        break

# Cell 3: Mock Pipeline Simulation
for cell in nb["cells"]:
    if cell["cell_type"] == "code" and "def vision_transcriber_node(" in "".join(cell["source"]):
        cell["source"] = [
            "# Cell 3: Mock Pipeline Simulation\n",
            "def extraction_node(state: AgentState) -> AgentState:\n",
            "    print(\"--> [Cluster A] Processing extraction (PyMuPDF / LLaVA)...\")\n",
            "    state[\"original_transcript\"] = f\"Processed content from {state['input_type']}\"\n",
            "    return state\n",
            "\n",
            "def teacher_node(state: AgentState) -> AgentState:\n",
            "    print(\"--> [Cluster A] Teacher Node: Creating final lesson (Qwen 2.5)...\")\n",
            "    state[\"final_lesson\"] = \"Welcome to the lesson! Today we cover...\"\n",
            "    return state\n",
            "\n",
            "def reviewer_node(state: AgentState) -> AgentState:\n",
            "    print(\"--> [Cluster A] Reviewer Node: Reviewing output...\")\n",
            "    return state\n",
            "\n",
            "def e2b_sandbox_node(state: AgentState) -> AgentState:\n",
            "    print(\"--> [Cluster B] E2B Sandbox Node: Executing code...\")\n",
            "    if state[\"input_data\"] == \"trigger_error\":\n",
            "        print(\"    [!] Execution failed!\")\n",
            "        state[\"execution_error\"] = \"SyntaxError: invalid syntax\"\n",
            "    else:\n",
            "        print(\"    [+] Execution succeeded!\")\n",
            "        state[\"execution_error\"] = \"\"\n",
            "    return state\n",
            "\n",
            "def deepseek_debugger_node(state: AgentState) -> AgentState:\n",
            "    print(\"--> [Cluster B] DeepSeek Debugger Node: Fixing code...\")\n",
            "    state[\"execution_error\"] = \"\"\n",
            "    state[\"input_data\"] = \"fixed_code\"\n",
            "    return state\n",
            "\n",
            "# Pipeline A Graph\n",
            "pipeline_a = StateGraph(AgentState)\n",
            "pipeline_a.add_node(\"extraction\", extraction_node)\n",
            "pipeline_a.add_node(\"teacher\", teacher_node)\n",
            "pipeline_a.add_node(\"reviewer\", reviewer_node)\n",
            "pipeline_a.set_entry_point(\"extraction\")\n",
            "pipeline_a.add_edge(\"extraction\", \"teacher\")\n",
            "pipeline_a.add_edge(\"teacher\", \"reviewer\")\n",
            "pipeline_a.add_edge(\"reviewer\", END)\n",
            "app_a = pipeline_a.compile()\n",
            "\n",
            "# Pipeline B Graph (Debug Loop only triggered manually)\n",
            "pipeline_b = StateGraph(AgentState)\n",
            "pipeline_b.add_node(\"e2b_sandbox\", e2b_sandbox_node)\n",
            "pipeline_b.add_node(\"deepseek_debugger\", deepseek_debugger_node)\n",
            "pipeline_b.set_entry_point(\"e2b_sandbox\")\n",
            "pipeline_b.add_edge(\"e2b_sandbox\", END)\n",
            "pipeline_b.add_edge(\"deepseek_debugger\", \"e2b_sandbox\")\n",
            "app_b = pipeline_b.compile()\n",
            "\n",
            "from IPython.display import display, Image\n",
            "try:\n",
            "    display(Image(app_a.get_graph().draw_mermaid_png()))\n",
            "    display(Image(app_b.get_graph().draw_mermaid_png()))\n",
            "except Exception:\n",
            "    pass\n",
            "\n",
            "def run_mock_pipeline_a(input_data: str, input_type: str):\n",
            "    print(f\"\\n{'='*50}\\nStarting Pipeline A Simulation: {input_type.upper()}\\n{'='*50}\")\n",
            "    \n",
            "    initial_state = {\n",
            "        \"input_data\": input_data,\n",
            "        \"input_type\": input_type,\n",
            "        \"original_transcript\": \"\",\n",
            "        \"bullet_points\": \"\",\n",
            "        \"final_lesson\": \"\",\n",
            "        \"execution_error\": \"\",\n",
            "        \"code_language\": \"python\",\n",
            "        \"is_vision_only\": input_type == \"image\",\n",
            "        \"is_code_request\": False\n",
            "    }\n",
            "    \n",
            "    for event in app_a.stream(initial_state):\n",
            "        for key, value in event.items():\n",
            "            print(f\"Finished {key}\")\n",
            "            print_state_audit(value)\n",
            "\n",
            "def run_mock_pipeline_b(input_data: str, is_debug: bool = False):\n",
            "    print(f\"\\n{'='*50}\\nStarting Pipeline B Simulation: {'DEBUG' if is_debug else 'EXECUTE'}\\n{'='*50}\")\n",
            "    \n",
            "    initial_state = {\n",
            "        \"input_data\": input_data,\n",
            "        \"input_type\": \"code\",\n",
            "        \"original_transcript\": \"\",\n",
            "        \"bullet_points\": \"\",\n",
            "        \"final_lesson\": \"\",\n",
            "        \"execution_error\": \"\",\n",
            "        \"code_language\": \"python\",\n",
            "        \"is_vision_only\": False,\n",
            "        \"is_code_request\": True\n",
            "    }\n",
            "    \n",
            "    if is_debug:\n",
            "        state = initial_state.copy()\n",
            "        state = deepseek_debugger_node(state)\n",
            "        state = e2b_sandbox_node(state)\n",
            "        print(\"Finished Debug Loop\")\n",
            "        print_state_audit(state)\n",
            "    else:\n",
            "        for event in app_b.stream(initial_state):\n",
            "            for key, value in event.items():\n",
            "                print(f\"Finished {key}\")\n",
            "                print_state_audit(value)\n",
            "\n",
            "print(\"Cell 3 Executed: Pipeline Nodes and Simulation Function Defined.\")\n"
        ]
        break

# Cell 5: Running tests
for cell in nb["cells"]:
    if cell["cell_type"] == "code" and "run_mock_pipeline(\"image_data_base64" in "".join(cell["source"]):
        cell["source"] = [
            "# Simulate Pipeline A for Multimodal Inputs\n",
            "run_mock_pipeline_a(\"image_data_base64\", \"image\")\n",
            "run_mock_pipeline_a(\"pdf_text_data\", \"pdf\")\n",
            "run_mock_pipeline_a(\"youtube_transcript\", \"video\")\n",
            "\n",
            "# Simulate Pipeline B for Execution and Debug\n",
            "run_mock_pipeline_b(\"valid_code\", is_debug=False)\n",
            "run_mock_pipeline_b(\"trigger_error\", is_debug=True)\n"
        ]
        break

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

