"""
routers/upload.py — POST /upload endpoint (Phase 5: Code Execution).

Implements a dynamic routing system for uploaded files:

  LANE 1 — Fast Digital (PyMuPDF)
    • Trigger:  PDF + force_vision=False  (default)
    • Method:   fitz in-memory text extraction — no model calls

  LANE 2 — Heavy Vision (LLaVA via Ollama)
    • Trigger:  PDF + force_vision=True
    • Method:   Slice PDF into per-page PNGs → LLaVA vision loop

  LANE 3 — Direct Image (LLaVA via Ollama)
    • Trigger:  image/* MIME type
    • Method:   Raw image bytes → Base64 → LLaVA single-shot

After extraction, the text is routed through the LangGraph orchestrator:
  Teacher → Code Extractor → Execution (Docker sandbox) → Debugger Loop → END

The response is returned as JSON matching the ChatResponse schema.
"""

from fastapi import APIRouter, HTTPException, Request, UploadFile, File, Form

from schemas import ChatResponse
from services.pdf_parser import extract_text_from_pdf
from services.llava_vision import (
    extract_text_from_image,
    extract_text_from_pdf_vision,
)
from services.orchestrator import run_upload_workflow
from services.tts import generate_tts_audio

router = APIRouter(tags=["Upload"])


@router.post("/upload", response_model=ChatResponse)
async def upload_file(
    request: Request,
    file: UploadFile = File(...),
    prompt: str | None = Form(None),
    force_vision: bool = Form(False),
):
    """
    Accept an uploaded file (image or PDF) and return an AI-generated lesson
    based on the extracted content.

    The lesson is generated by the LangGraph orchestrator, which also
    extracts any Python code examples, runs them in a Docker sandbox,
    and self-corrects errors up to 3 times.

    Args:
        request:       The FastAPI Request (used for disconnect detection).
        file:          The uploaded file (PDF or image).
        prompt:        Optional student question / context.
        force_vision:  If True and file is a PDF, routes through LLaVA
                       vision instead of PyMuPDF text extraction.

    Returns:
        ChatResponse with { explanation, audio_base64 }.
    """
    # ------------------------------------------------------------------
    # 0. Read and validate the upload
    # ------------------------------------------------------------------
    file_bytes = await file.read()
    if not file_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    content_type = file.content_type or ""
    user_prompt = prompt.strip() if prompt and prompt.strip() else None

    print("=" * 60)
    print(f"[Upload] New file received")
    print(f"  filename      : {file.filename}")
    print(f"  content_type  : {content_type}")
    print(f"  size          : {len(file_bytes):,} bytes")
    print(f"  force_vision  : {force_vision}")
    print(f"  user_prompt   : {user_prompt or '(none)'}")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. Text Extraction — route to the correct pipeline
    # ------------------------------------------------------------------
    extracted_text = ""

    try:
        if content_type == "application/pdf":
            if force_vision:
                # ── LANE 2: Heavy Vision — PDF → page images → LLaVA ──
                print("[Upload] Handwritten PDF → routing to LLaVA vision loop")
                extracted_text = await extract_text_from_pdf_vision(file_bytes)
            else:
                # ── LANE 1: Fast Digital — PDF → PyMuPDF ──
                print("[Upload] Digital PDF → routing to PyMuPDF fast extraction")
                extracted_text = extract_text_from_pdf(file_bytes)

        elif content_type.startswith("image/"):
            # ── LANE 3: Direct Image — image → LLaVA ──
            print("[Upload] Image upload → routing to LLaVA")
            extracted_text = await extract_text_from_image(file_bytes)

        else:
            raise HTTPException(
                status_code=400,
                detail=(
                    f"Unsupported file type: {content_type}. "
                    "Please upload a PDF or image (PNG, JPEG, etc.)."
                ),
            )

    except HTTPException:
        raise
    except Exception as exc:
        print(f"[Upload] Extraction error: {exc}")
        raise HTTPException(
            status_code=500,
            detail=f"Text extraction failed: {exc}",
        ) from exc

    # Guard: nothing usable was extracted
    if not extracted_text or not extracted_text.strip():
        raise HTTPException(
            status_code=422,
            detail=(
                "No readable content could be extracted from the uploaded file. "
                "If this is a scanned or handwritten PDF, try re-uploading with "
                "the handwriting toggle enabled."
            ),
        )

    print(
        f"[Upload] Extraction complete — {len(extracted_text):,} characters. "
        f"Handing off to LangGraph orchestrator..."
    )

    # ------------------------------------------------------------------
    # 2. LangGraph Orchestrator
    #    Teacher → Code Extractor → Execution → Debugger Loop → END
    # ------------------------------------------------------------------
    try:
        explanation = await run_upload_workflow(
            extracted_text=extracted_text,
            user_prompt=user_prompt,
        )
    except Exception as exc:
        print(f"[Upload] Orchestrator error: {exc}")
        raise HTTPException(
            status_code=502,
            detail=f"Lesson generation failed: {exc}",
        ) from exc

    print(f"[Upload] Lesson generated — {len(explanation):,} characters.")

    # ------------------------------------------------------------------
    # 3. TTS (skip if client already disconnected)
    # ------------------------------------------------------------------
    audio_base64 = None
    if not await request.is_disconnected():
        audio_base64 = generate_tts_audio(explanation)

    return ChatResponse(
        explanation=explanation,
        audio_base64=audio_base64,
    )

